### ISSUE TITLE
metaissue: create exercises for all sections

### ISSUE THREAD

**Issue by satra** [ReproNim/ohbm2018-training#6]
1. FAIR Data - BIDS datasets
talk 1: Intro to FAIR
- [ ] exercise: 16 attributes of FAIR - e.g. Is there a clear license, what is a PID, What is meant by metadata, … 
link attributes for 2 modules below 
talk 2: Standardization and BIDS
- [ ] exercise: dicom to BIDS conversion exercise: basic conversion (tie in w/ ReproIn in next section)
talk 3: FAIR Metadata: searching and using Scicrunch
- [ ] exercise: BIDS metadata - participants.tsv and semantic annotation
talk 4: Brief Intro to NIDM
- [ ] exercise: NIDM conversion tool to create sidecar file

2. Computational basis
talk 1: ReproIn : More on this?
- [ ] Exercise: 
talk 2: Git/GitAnnex/DataLad: 
- [ ] Exercise: 
talk 3: Everything Else 
- [ ] Exercise: 

3. Neuroimaging Workflows
talk 1: ReproFlow: Reusable scripts and environments, PROV
- [ ] Exercise: Run, rinse, and repeat
talk 2: ReproEnv: Virtual machines/ContainersReproPaper, NIDM components
- [ ] Exercise: Create different environments 
[talk 3: ReproTest: Variability sources (analysis models, operating systems, software versions)]
- [ ] Exercise: Run analysis with different environments

4.  Statistics for reproducibility
Assumes we have a csv file with say 100 subjects and columns like: “age, sex, pheno1, pheno2… “
talk 1: evil p-value : what they are - and are not
- [ ] Exercise: test with   
talk 2: 
- [ ] Exercise: 
talk 3: 
- [ ] Exercise: 

16:00-16:30  Conclusion & Getting Feedback
Nina Preuss, Preuss Enterprises, United States
- [ ] Surveys

**Comment by satra** [comment]
in general, perhaps 10 min talks + 15 min hands on exercises, which should leave a bit of slop factor and time for questions in each section.
